// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for content documents
 */
interface ContentDocumentData {
  /**
   * texto field in *content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.texto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texto: prismic.RichTextField;
}

/**
 * content document from Prismic
 *
 * - **API ID**: `content`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentDocumentData>,
    "content",
    Lang
  >;

type PaginaDocumentDataSlicesSlice = never;

/**
 * Content for pagina documents
 */
interface PaginaDocumentData {
  /**
   * content field in *pagina*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pagina.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * titulo field in *pagina*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pagina.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Slice Zone field in *pagina*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pagina.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PaginaDocumentDataSlicesSlice>; /**
   * Meta Title field in *pagina*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pagina.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *pagina*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pagina.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *pagina*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pagina.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * pagina document from Prismic
 *
 * - **API ID**: `pagina`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PaginaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PaginaDocumentData>, "pagina", Lang>;

type PitemexpandindoDocumentDataSlicesSlice = ItemExpandindoSlice;

/**
 * Content for PItemExpandindo documents
 */
interface PitemexpandindoDocumentData {
  /**
   * titulo field in *PItemExpandindo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: titulo da pagina (aparece no botao)
   * - **API ID Path**: pitemexpandindo.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * conteudo_inicial field in *PItemExpandindo*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Conteudo introdutório
   * - **API ID Path**: pitemexpandindo.conteudo_inicial
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  conteudo_inicial: prismic.RichTextField;

  /**
   * Slice Zone field in *PItemExpandindo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pitemexpandindo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PitemexpandindoDocumentDataSlicesSlice>; /**
   * Meta Title field in *PItemExpandindo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pitemexpandindo.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *PItemExpandindo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pitemexpandindo.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *PItemExpandindo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pitemexpandindo.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * PItemExpandindo document from Prismic
 *
 * - **API ID**: `pitemexpandindo`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PitemexpandindoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PitemexpandindoDocumentData>,
    "pitemexpandindo",
    Lang
  >;

export type AllDocumentTypes =
  | ContentDocument
  | PaginaDocument
  | PitemexpandindoDocument;

/**
 * Primary content in *ItemExpandindo → Default → Primary*
 */
export interface ItemExpandindoSliceDefaultPrimary {
  /**
   * titulo field in *ItemExpandindo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: titulo
   * - **API ID Path**: item_expandindo.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * texto field in *ItemExpandindo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: texto
   * - **API ID Path**: item_expandindo.default.primary.texto
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texto: prismic.RichTextField;
}

/**
 * Default variation for ItemExpandindo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ItemExpandindoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ItemExpandindoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ItemExpandindo*
 */
type ItemExpandindoSliceVariation = ItemExpandindoSliceDefault;

/**
 * ItemExpandindo Shared Slice
 *
 * - **API ID**: `item_expandindo`
 * - **Description**: ItemExpandindo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ItemExpandindoSlice = prismic.SharedSlice<
  "item_expandindo",
  ItemExpandindoSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContentDocument,
      ContentDocumentData,
      PaginaDocument,
      PaginaDocumentData,
      PaginaDocumentDataSlicesSlice,
      PitemexpandindoDocument,
      PitemexpandindoDocumentData,
      PitemexpandindoDocumentDataSlicesSlice,
      AllDocumentTypes,
      ItemExpandindoSlice,
      ItemExpandindoSliceDefaultPrimary,
      ItemExpandindoSliceVariation,
      ItemExpandindoSliceDefault,
    };
  }
}
